### ISSUE TITLE
CloudFront経由で動的なDjangoアプリに外部からアクセスする

### ISSUE THREAD

**Issue by daisakuhazui** [daisakuhazui/Steady-Progress#8]
## Summary
プロジェクトで必要なCloudFrontの扱いを理解する。
## TODO
- [x] Django公式チュートリアルを終わらせる #6 
- [x] CloudFront でDestribution を設定する
- [x] EC2にDjandoアプリをアップロードする（git clone)
- [x] CloudFront とEC2を接続する
- [ ] 外部からCloudFront経由でアクセスしてGET ／PUTメソッドを投げてみる
